new: add unified scipt file

diff --git a/build-dav1d b/build-dav1d
--- a/build-dav1d
+++ b/build-dav1d
@@ -1,13 +1,24 @@
-#!/usr/bin/env bash -e
+#!/usr/bin/env zsh -e
 #
 # dav1d
 # https://code.videolan.org/videolan/dav1d.git
 #
+
+set -e
+
+PS4='+ ${BASH_SOURCE}:${LINENO}: '
+
+error_report() {
+    echo "Error on line $1"
+}
+
+trap 'error_report $LINENO' ERR
+
 cd "$(dirname "$0")"
 set -a; source build.env; set +a
 
 pkgname="dav1d"
-pkgdir="/opt/local/${pkgname}"
+pkgdir="$1"
 srcdir="src/dav1d"
 builddir="${TMPDIR:-/tmp}/build.${pkgname}"
 
@@ -21,11 +32,11 @@ meson setup "${builddir}" "${srcdir}" \
   -Db_lto_mode=thin \
   -Denable_tools=false \
   -Denable_tests=false \
-  "$@"
+  # "$@"
 
 meson compile -C "${builddir}"
 
-rm -rf "${pkgdir}"
+# rm -rf "${pkgdir}"
 
 meson install -C "${builddir}"
 
diff --git a/build-ffmpeg b/build-ffmpeg
--- a/build-ffmpeg
+++ b/build-ffmpeg
@@ -1,34 +1,39 @@
-#!/usr/bin/env bash -e
+#!/usr/bin/env zsh -e
 #
 # FFmpeg
 # https://git.ffmpeg.org/ffmpeg.git
 #
+
+set -e
+
+PS4='+ ${BASH_SOURCE}:${LINENO}: '
+
+error_report() {
+    echo "Error on line $1"
+}
+
+trap 'error_report $LINENO' ERR
+
 cd "$(dirname "$0")"
 set -a; source build.env; set +a
 source utils/pkg-import
 
 pkgname="ffmpeg"
-pkgdir="/opt/local/${pkgname}"
+pkgdir="$1"
 srcdir="src/ffmpeg"
 
-import_local_pkg dav1d
-import_local_pkg freetype
-import_local_pkg harfbuzz
-import_local_pkg libass
-import_local_pkg libplacebo
-import_local_pkg vulkan
+import_local_pkg $pkgdir
 
 cd "${srcdir}"
 
 ./configure \
   --prefix="${pkgdir}" \
   --pkg-config="${PKG_CONFIG}" \
-  --arch="$(uname -m)" \
+  --arch="$(arch)" \
   --cpu=host \
   --cc=clang \
-  --extra-cflags="-I$(brew --prefix)/include" \
-  --extra-ldflags="-L$(brew --prefix)/lib -Wl,-ld_classic" \
   --enable-shared \
+  --enable-ffplay \
   --enable-lto \
   --enable-gpl \
   --enable-version3 \
@@ -59,13 +64,13 @@ cd "${srcdir}"
   --disable-sdl2 \
   --disable-libxcb \
   --disable-xlib \
-  "$@"
+  # "$@"
 
-make -j4
+make -j$(sysctl -n hw.physicalcpu)
 
-rm -rf "${pkgdir}"
+# rm -rf "${pkgdir}"
 
 make install
-rm -rf "${pkgdir}"/share
+# rm -rf "${pkgdir}"/share
 
 # vi:set ts=2 sw=2 et:
diff --git a/build-freetype b/build-freetype
--- a/build-freetype
+++ b/build-freetype
@@ -1,19 +1,29 @@
-#!/usr/bin/env bash -e
+#!/usr/bin/env zsh -e
 #
 # FreeType
 # https://gitlab.freedesktop.org/freetype/freetype.git
 #
+
+set -e
+
+PS4='+ ${BASH_SOURCE}:${LINENO}: '
+
+error_report() {
+    echo "Error on line $1"
+}
+
+trap 'error_report $LINENO' ERR
+
 cd "$(dirname "$0")"
 set -a; source build.env; set +a
 source utils/pkg-import
 
 pkgname="freetype"
-pkgdir="/opt/local/${pkgname}"
+pkgdir=$(echo "$1" | awk -F= '{print $2}')
 srcdir="src/freetype"
 builddir="${TMPDIR:-/tmp}/build.${pkgname}"
 
-import_local_pkg freetype
-import_local_pkg harfbuzz
+import_local_pkg $pkgdir
 
 rm -rf "${builddir}"
 
@@ -33,7 +43,7 @@ meson setup "${builddir}" "${srcdir}" \
 
 meson compile -C "${builddir}"
 
-rm -rf "${pkgdir}"
+# rm -rf "${pkgdir}"
 
 meson install -C "${builddir}"
 
diff --git a/build-harfbuzz b/build-harfbuzz
--- a/build-harfbuzz
+++ b/build-harfbuzz
@@ -1,19 +1,29 @@
-#!/usr/bin/env bash -e
+#!/usr/bin/env zsh -e
 #
 # HarfBuzz
 # https://github.com/harfbuzz/harfbuzz.git
 #
+
+set -e
+
+PS4='+ ${BASH_SOURCE}:${LINENO}: '
+
+error_report() {
+    echo "Error on line $1"
+}
+
+trap 'error_report $LINENO' ERR
+
 cd "$(dirname "$0")"
 set -a; source build.env; set +a
 source utils/pkg-import
 
 pkgname="harfbuzz"
-pkgdir="/opt/local/${pkgname}"
+pkgdir="$1"
 srcdir="src/harfbuzz"
 builddir="${TMPDIR:-/tmp}/build.${pkgname}"
 
-import_local_pkg freetype
-import_local_pkg harfbuzz
+import_local_pkg $pkgdir
 
 rm -rf "${builddir}"
 
@@ -34,11 +44,11 @@ meson setup "${builddir}" "${srcdir}" \
   -Dintrospection=disabled \
   -Ddocs=disabled \
   -Dutilities=disabled \
-  "$@"
+  # "$@"
 
 meson compile -C "${builddir}"
 
-rm -rf "${pkgdir}"
+# rm -rf "${pkgdir}"
 
 meson install -C "${builddir}"
 
diff --git a/build-libass b/build-libass
--- a/build-libass
+++ b/build-libass
@@ -1,18 +1,28 @@
-#!/usr/bin/env bash -e
+#!/usr/bin/env zsh -e
 #
 # libass
 # https://github.com/libass/libass.git
 #
+
+set -e
+
+PS4='+ ${BASH_SOURCE}:${LINENO}: '
+
+error_report() {
+    echo "Error on line $1"
+}
+
+trap 'error_report $LINENO' ERR
+
 cd "$(dirname "$0")"
 set -a; source build.env; set +a
 source utils/pkg-import
 
 pkgname="libass"
-pkgdir="/opt/local/${pkgname}"
+pkgdir="$1"
 srcdir="src/libass"
 
-import_local_pkg freetype
-import_local_pkg harfbuzz
+import_local_pkg $pkgdir
 
 export CFLAGS="${CFLAGS} -O3 -flto=thin"
 
@@ -29,11 +39,11 @@ cd "${srcdir}"
   --enable-libunibreak \
   --enable-asm \
   --disable-fontconfig \
-  "$@"
+  # "$@"
 
-make -j4
+make -j$(sysctl -n hw.physicalcpu)
 
-rm -rf "${pkgdir}"
+# rm -rf "${pkgdir}"
 
 make install
 
diff --git a/build-libplacebo b/build-libplacebo
--- a/build-libplacebo
+++ b/build-libplacebo
@@ -1,44 +1,60 @@
-#!/usr/bin/env bash -e
+#!/usr/bin/env zsh -e
 #
 # libplacebo
 # https://code.videolan.org/videolan/libplacebo.git
 #
+
+set -e
+
+PS4='+ ${BASH_SOURCE}:${LINENO}: '
+
+error_report() {
+    echo "Error on line $1"
+}
+
+trap 'error_report $LINENO' ERR
+
 cd "$(dirname "$0")"
 set -a; source build.env; set +a
 source utils/pkg-import
 
 pkgname="libplacebo"
-pkgdir="/opt/local/${pkgname}"
+pkgdir="$1"
 srcdir="src/libplacebo"
-builddir="${TMPDIR:-/tmp}/build.${pkgname}"
+builddir="${TMPDIR:-/tmp}/build.$pkgname"
 
-import_local_pkg vulkan
+import_local_pkg $pkgdir
+echo $PKG_CONFIG_PATH
+echo $CPPFLAGS
+echo $LDFLAGS
+# import_homebrew_pkg glslang
+# import_homebrew_pkg spirv-tools
 
 rm -rf "${builddir}"
 
-meson setup "${builddir}" "${srcdir}" \
-  --prefix="${pkgdir}" \
+meson setup "$builddir" "$srcdir" \
+  --prefix="$pkgdir" \
   -Dwrap_mode=nodownload \
   -Dbuildtype=release \
   -Db_lto=true \
   -Db_lto_mode=thin \
-  -Dvulkan-registry="/opt/local/vulkan/share/vulkan/registry/vk.xml" \
+  -Dvulkan-registry="$pkgdir/share/vulkan/registry/vk.xml" \
   -Dvulkan=enabled \
   -Dshaderc=enabled \
   -Dlcms=enabled \
   -Dxxhash=enabled \
-  -Dopengl=disabled \
-  -Dd3d11=disabled \
+  -Dopengl=enabled \
   -Dglslang=disabled \
+  -Dd3d11=disabled \
   -Ddemos=false \
-  "$@"
+  # "$@"
 
-meson compile -C "${builddir}"
+meson compile -C "$builddir"
 
-rm -rf "${pkgdir}"
+# rm -rf "${pkgdir}"
 
-meson install -C "${builddir}"
+meson install -C "$builddir"
 
-rm -rf "${builddir}"
+rm -rf "$builddir"
 
 # vi:set ts=2 sw=2 et:
diff --git a/build-moltenvk b/build-moltenvk
--- a/build-moltenvk
+++ b/build-moltenvk
@@ -1,28 +1,39 @@
-#!/usr/bin/env bash -e
+#!/usr/bin/env zsh -e
 #
 # MoltenVK
 # https://github.com/KhronosGroup/MoltenVK.git
 #
+
+set -e
+
+PS4='+ ${BASH_SOURCE}:${LINENO}: '
+
+error_report() {
+    echo "Error on line $1"
+}
+
+trap 'error_report $LINENO' ERR
+
 cd "$(dirname "$0")"
 set -a; source build.env; set +a
 
 pkgname="moltenvk"
-pkgdir="/opt/local/${pkgname}"
+pkgdir="$1"
 srcdir="src/MoltenVK"
 builddir="Package/Latest/MoltenVK/dylib/macOS"
 
-cd "${srcdir}"
+cd "$srcdir"
 
 ./fetchDependencies \
   --macos \
-  --v-headers-root /opt/local/vulkan
+  --v-headers-root $pkgdir
 
 make macos MVK_CONFIG_LOG_LEVEL=2
 
 sed -i '' "s|./libMoltenVK|${pkgdir}/lib/libMoltenVK|g" "${builddir}"/MoltenVK_icd.json
 cat "${builddir}"/MoltenVK_icd.json
 
-rm -rf "${pkgdir}"
+# rm -rf "${pkgdir}"
 
 mkdir -p "${pkgdir}"/lib "${pkgdir}"/share/vulkan/icd.d
 install -vm755 "${builddir}"/libMoltenVK.dylib "${pkgdir}"/lib
diff --git a/build-mpv b/build-mpv
--- a/build-mpv
+++ b/build-mpv
@@ -1,28 +1,35 @@
-#!/usr/bin/env bash -e
+#!/usr/bin/env zsh -e
 #
 # mpv
 # https://github.com/mpv-player/mpv.git
 #
+
+set -e
+
+PS4='+ ${BASH_SOURCE}:${LINENO}: '
+
+error_report() {
+    echo "Error on line $1"
+}
+
+trap 'error_report $LINENO' ERR
+
 cd "$(dirname "$0")"
 set -a; source build.env; set +a
 source utils/pkg-import
 
 pkgname="mpv"
-pkgdir="/opt/local/${pkgname}"
+pkgdir="$1"
+with_bundle="$2"
 srcdir="src/mpv"
-builddir="${TMPDIR:-/tmp}/build.${pkgname}"
+builddir="$srcdir/build"
 
-import_local_pkg dav1d
-import_local_pkg ffmpeg
-import_local_pkg freetype
-import_local_pkg harfbuzz
-import_local_pkg libass
-import_local_pkg libplacebo
-import_local_pkg vulkan
+import_local_pkg $pkgdir
 
 import_homebrew_pkg libarchive
 
 rm -rf "${builddir}"
+sed -i -e 's/UNKNOWN/1/g' "$srcdir/VERSION"
 
 meson setup "${builddir}" "${srcdir}" \
   --prefix="${pkgdir}" \
@@ -32,14 +39,21 @@ meson setup "${builddir}" "${srcdir}" \
   -Db_lto_mode=thin \
   -Dlua=luajit \
   -Dmacos-touchbar=disabled \
-  "$@"
+  # "$@"
 
-meson compile -C "${builddir}"
+meson compile -j$(sysctl -n hw.physicalcpu) -C "${builddir}"
 
-rm -rf "${pkgdir}"
+# rm -rf "${pkgdir}"
 
 meson install -C "${builddir}" --tags runtime,devel
 
-rm -rf "${builddir}"
+if [ "$with_bundle" -eq 1 ]; then
+  cd $srcdir
+  ./TOOLS/osxbundle.py -s build/mpv
+fi
 
+# rm -rf "${builddir}"
+cd "$(dirname "$0")"
+git -C "$srcdir" restore VERSION
+git -C "$srcdir" clean -f VERSION-e
 # vi:set ts=2 sw=2 et:
diff --git a/build-vulkan b/build-vulkan
--- a/build-vulkan
+++ b/build-vulkan
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash -e
+#!/usr/bin/env zsh -e
 #
 # Vulkan Headers
 # https://github.com/KhronosGroup/Vulkan-Headers.git
@@ -6,21 +6,32 @@
 # Vulkan Loader
 # https://github.com/KhronosGroup/Vulkan-Loader.git
 #
+
+set -e
+
+PS4='+ ${BASH_SOURCE}:${LINENO}: '
+
+error_report() {
+    echo "Error on line $1"
+}
+
+trap 'error_report $LINENO' ERR
+
 cd "$(dirname "$0")"
 set -a; source build.env; set +a
 
 pkgname="vulkan"
-pkgdir="/opt/local/${pkgname}"
+pkgdir="$1"
 headerssrcdir="src/Vulkan-Headers"
 loadersrcdir="src/Vulkan-Loader"
 builddir="${TMPDIR:-/tmp}/build.${pkgname}"
 
 icddatadirs=(
-  "/opt/local/moltenvk/share"
+  "$1/share"
   "/usr/local/share"
 )
 
-rm -rf "${builddir}" "${pkgdir}"
+rm -rf "${builddir}" # "${pkgdir}"
 
 cmake \
   -B "${builddir}" \
@@ -42,7 +53,7 @@ cmake \
   -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
   -DVULKAN_HEADERS_INSTALL_DIR="${pkgdir}" \
   -DFALLBACK_DATA_DIRS="$( IFS=:; echo "${icddatadirs[*]}" )" \
-  "$@"
+  # "$@"
 
 cmake --build "${builddir}"
 cmake --install "${builddir}"
diff --git a/utils/pkg-import b/utils/pkg-import
--- a/utils/pkg-import
+++ b/utils/pkg-import
@@ -1,14 +1,14 @@
 #!/hint/bash
 
 import_local_pkg() {
-  local pkgname="$1"
-  local pcdir="/opt/local/${pkgname}/lib/pkgconfig"
+  local prefix="$1"
+  local pcdir="$prefix/lib/pkgconfig"
   local pcpath="${PKG_CONFIG_PATH:+${PKG_CONFIG_PATH}:}"
 
-  if [ $# != 1 ] || [ -z "${pkgname}" ]; then
-    echo -e "\033[1;31mERROR\033[0m ${FUNCNAME}: invalid argument."
-    exit 1
-  fi
+  # if [ $# != 1 ] || [ -z "${pkgname}" ]; then
+  #   echo -e "\033[1;31mERROR\033[0m ${FUNCNAME}: invalid argument."
+  #   exit 1
+  # fi
 
   if [ ! -d "${pcdir}" ]; then
     echo -e "\033[1;33mWARNING\033[0m ${FUNCNAME}: ${pcdir} does not exist."
